name: ubuntu

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: make update-init update-modules

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true

      - uses: actions/cache@v2
        with:
          path: ~/.fontist
          key: fontist-ubuntu
          restore-keys: fontist-ubuntu

      # cabextract for fonts, gettext-base for envsubst, libxml2-utils for xmllint
      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get -y install gettext-base cabextract libxml2-utils curl \
            software-properties-common gcc ruby ruby-dev libffi-dev make libxml2-dev libxslt1-dev

      - name: Install Fontist fonts
        run: |
          gem install fontist
          fontist update
          fontist manifest-install --confirm-license fonts/manifest.yml
          fontist manifest-locations fonts/manifest.yml > fonts/manifest.paths.yml
          cat fonts/manifest.paths.yml

      - run: make all published
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}

      - uses: actions/upload-artifact@master
        with:
          name: published-ubuntu
          path: published

      - uses: actions/upload-artifact@master
        with:
          name: xslt
          path: xslt

  deploy-gh-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master

    - uses: actions/download-artifact@master
      with:
        name: published-ubuntu
        path: published

    - name: GitHub Pages action
      uses: docker://peaceiris/gh-pages:v2
      with:
        emptyCommits: false
        forceOrphan: true
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./published

    - uses: actions/download-artifact@master
      with:
        name: xslt
        path: xslt

    - name: Update XSLTs in processor gems
      env:
        GIT_CREDS: metanorma-ci:${{ secrets.METANORMA_CI_PAT_TOKEN }}@
      run: |
        git config --global user.name "metanorma-ci"
        git config --global user.email "metanorma-ci@users.noreply.github.com"
        make update-xslts-in-processor-all

    - uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN || secrets.GITHUB_TOKEN }}
        repository: metanorma/mn-native-pdf-bsi
        event-type: metanorma/mn-native-pdf

    - uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN || secrets.GITHUB_TOKEN }}
        repository: metanorma/mn-native-pdf-nist
        event-type: metanorma/mn-native-pdf
