name: ubuntu

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # cabextract for fonts, gettext-base for envsubst, libxml2-utils for xmllint
      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get -y install gettext-base cabextract wget p7zip-full libxml2-utils

          # Install fontforge
          sudo apt-get -y install software-properties-common
          sudo add-apt-repository ppa:fontforge/fontforge
          sudo apt-get update
          sudo apt-get -y install fontforge

          # Install fonts
          sudo apt-get -y install fonts-freefont-ttf fonts-nanum fonts-droid-fallback

          # If necessary
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install ttf-mscorefonts-installer

      - name: Setup Cambria fonts
        run: |
          # Setup Cambria
          curl -Ls https://gist.github.com/maxwelleite/10774746/raw/ttf-vista-fonts-installer.sh | sudo bash
          sudo chown -R $(whoami) /usr/share/fonts/
          mkdir -p ~/.fonts
          cp -a /usr/share/fonts/* ~/.fonts
          ls -alR ~/.fonts

      - name: Setup CJK fonts
        run: |
          cd ~/.fonts
          curl -Ls https://github.com/Pal3love/Source-Han-TrueType/raw/master/SourceHanSans.7z -o ~/.fonts/hansans.7z
          7z x hansans.7z
          ls -alR ~/.fonts

      - uses: actions/checkout@master

      - name: Update submodules
        run: |
          make update-init update-modules

      - name: Compile output
        env:
          MN_PDF_FONT_PATH: ~/.fonts
        run: |
          make all
          mv documents published

      - uses: actions/upload-artifact@master
        with:
          name: published-ubuntu
          path: published


  deploy-gh-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: published-ubuntu
        path: published

    - name: GitHub Pages action
      uses: docker://peaceiris/gh-pages:v2
      with:
        emptyCommits: false
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./published
