name: windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup prerequisites
        run: |
          choco install --no-progress make gnuwin32-coreutils.install curl xsltproc unzip
          make --version
          curl --version

      - uses: actions/checkout@master

      - name: Update gems
        run: |
          gem install bundler
          bundle config build.nokogiri --use-system-libraries
          bundle install --jobs 4 --retry 3

      - name: Update submodules
        run: |
          make -f Makefile.win update-init update-modules

      - name: Build
        run: |
          make -f Makefile.win all

      - name: Run tests
        env:
          MN_PDF_FONT_PATH: C:\Windows\Fonts
        run: |
          make -f Makefile.win test
