name: xml-fo

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup fonts # i.e. Cambria
        run: |
          sudo apt-get install -y cabextract
          mkdir -p ~/.fonts
          curl -s http://plasmasturm.org/dl/vistafonts-installer | sudo bash
      - name: Setup prerequisites
        run: |
          sudo apt-get -y install gettext-base
          sudo apt-get install -y fop
      - uses: actions/checkout@master
      - name: Set font directory
      env:
        FONT_PATH: ${{ secrets.GITHUB_REPOSITORY }}
        run: |
          envsubst < pdf_fonts_config.xml.in > pdf_fonts_config.xml
      - name: Build PDF document
        run: |
          fop -c pdf_fonts_config.xml -xml iso-24229.xml -xsl iso-24229.xsl -out application/pdf iso-24229.pdf
          mkdir -p published
          mv *.pdf published/
      - uses: actions/upload-artifact@master
        with:
          name: published
          path: published


  deploy-gh-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: published
    - name: deploy-to-gh
      env:
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GH_DEPLOY_KEY: ${{ secrets.GH_DEPLOY_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        curl -L https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/ghactions-deploy-to-gh-pages.sh | bash
